backpack-enhancer:
  levels:
    1:
      price: 1000
    2:
      price: 2000
    3:
      price: 3000
    4:
      price: 4000
    5:
      price: 5000
    6:
      price: 6000
command:
  names:
    - "vaultbackpackseller"
    - "vbps"
    - "money-backpack"
backpack-price: 50000